spring:
  application:
    name: arcturus-stream-api

  datasource:
    # 🚀 Agora aponta para o serviço 'db' do Docker Compose
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/arcturus_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:suasenha}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false # Desativado para economizar log/processamento na Micro
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    aws:
      region:
        static: us-east-1
      s3:
        region: us-east-1

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

aws:
  region: us-east-1
  s3:
    bucket: ${AWS_S3_BUCKET:arcturus-assets-sa-marianna}

jamendo:
  client-id: ${JAMENDO_CLIENT_ID:22d88624}
  url: https://api.jamendo.com/v3.0/tracks/

api:
  security:
    token:
      secret: ${JWT_SECRET:MinhaSenhaSuperSecretaDoArcturusProject123456}